# Generated by Django 2.1.3 on 2019-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classified',
            name='img_class',
        ),
        migrations.AddField(
            model_name='classified',
            name='img_class',
            field=models.ManyToManyField(to='file_manager.ImgClass'),
        ),
    ]
